language: python

addons:
  apt:
    sources:
      - sourceline: 'ppa:deadsnakes/ppa'
    packages:
      - python3.6-dev
      - gmsh

python:
  - "3.6"

before_install:
  - pip3 install -U -r test_requirements.txt

install:
  - pip3 install .

script:
  - cd $TRAVIS_BUILD_DIR/test
  - pytest --cov pymapping

after_success:
  - codecov
