language: python

addons:
  apt:
    sources:
      - sourceline: 'ppa:deadsnakes/ppa'
    packages:
      - swig
      - cmake
      - python3.6-dev

python:
  - "3.6"

before_install:
  - pip3 install -U -r test_requirements.txt

install:
  - pip3 install .

before_script:
  - wget --quiet http://files.salome-platform.org/Salome/other/medCoupling-9.3.0.tar.gz -O /tmp/medCoupling-9.3.0.tar.gz
  - cd /tmp && tar -xzvf medCoupling-9.3.0.tar.gz
  - cd MEDCOUPLING-9.3.0 && mkdir build && cd build
  - cmake -DCONFIGURATION_ROOT_DIR=../../CONFIGURATION_9.3.0 -DPYTHON_ROOT_DIR=$VIRTUAL_ENV -DCMAKE_INSTALL_PREFIX=$VIRTUAL_ENV -DMEDCOUPLING_MICROMED=ON -DMEDCOUPLING_BUILD_DOC=OFF -DMEDCOUPLING_ENABLE_PARTITIONER=OFF -DMEDCOUPLING_PARTITIONER_SCOTCH=OFF -DMEDCOUPLING_PARTITIONER_METIS=OFF -DMEDCOUPLING_BUILD_TESTS=OFF -DMEDCOUPLING_ENABLE_RENUMBER=OFF -DMEDCOUPLING_WITH_FILE_EXAMPLES=OFF ..
  - cmake --build . --config Release --target install
  - export LD_LIBRARY_PATH=$VIRTUAL_ENV/lib:$LD_LIBRARY_PATH

script:
  - cd $TRAVIS_BUILD_DIR/test
  - pytest --cov pymapping

after_success:
  - codecov
